import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Package from '../models/Package.js';

dotenv.config();

const image = (id, width = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85&crop=entropy&cs=tinysrgb`;

const commonIncluded = ['Accommodation', 'Breakfast', 'Local transfers', 'Guided experience', 'Government taxes'];
const commonExcluded = ['International flights', 'Personal expenses', 'Travel insurance', 'Tips and gratuities'];

const packages = [
  {
    title: 'Pokhara Luxury Lakeside Escape',
    slug: 'pokhara-luxury-lakeside-escape',
    location: 'Pokhara',
    category: 'Luxury',
    shortDescription: 'A refined lakeside stay with mountain views, spa time, and slow evenings by Phewa Lake.',
    description: 'Unwind in Pokhara with boutique accommodation, private lakeside moments, sunrise views of the Annapurna range, and curated dining near Phewa Lake.',
    price: 18500,
    durationDays: 3,
    durationNights: 2,
    maxGuests: 4,
    rating: 4.8,
    reviewsCount: 96,
    coverImage: image('photo-1501785888041-af3ef285b470'),
    images: [image('photo-1501785888041-af3ef285b470'), image('photo-1518684079-3c830dcef090'), image('photo-1520250497591-112f2f40a3f4')],
    amenities: ['Lake view room', 'Spa access', 'Breakfast', 'Airport pickup', 'Wi-Fi'],
    highlights: ['Phewa Lake boating', 'Sarangkot sunrise', 'Luxury lakeside stay', 'Annapurna views'],
    included: commonIncluded,
    excluded: commonExcluded,
    itinerary: [
      { day: 1, title: 'Arrival in Pokhara', description: 'Transfer to your lakeside hotel and enjoy a relaxed evening by Phewa Lake.' },
      { day: 2, title: 'Sunrise and Lakeside Leisure', description: 'Visit Sarangkot at sunrise, then enjoy boating, spa time, and lakeside dining.' },
      { day: 3, title: 'Slow Morning Departure', description: 'Breakfast with mountain views before checkout and transfer.' },
    ],
    isFeatured: true,
  },
  {
    title: 'Nagarkot Sunrise Weekend Retreat',
    slug: 'nagarkot-sunrise-weekend-retreat',
    location: 'Nagarkot',
    category: 'Relaxation',
    shortDescription: 'A quiet hilltop weekend built around Himalayan sunrise views and easy nature walks.',
    description: 'Escape Kathmandu for a calm Nagarkot retreat with forest trails, cozy lodging, and panoramic sunrise views across the Himalayas.',
    price: 9500,
    durationDays: 2,
    durationNights: 1,
    maxGuests: 3,
    rating: 4.6,
    reviewsCount: 74,
    coverImage: image('photo-1500534314209-a25ddb2bd429'),
    images: [image('photo-1500534314209-a25ddb2bd429'), image('photo-1500530855697-b586d89ba3ee'), image('photo-1500534314209-a25ddb2bd429')],
    amenities: ['Mountain view', 'Breakfast', 'Private transfer', 'Bonfire', 'Wi-Fi'],
    highlights: ['Nagarkot sunrise', 'Short nature walk', 'Hilltop resort stay', 'Kathmandu escape'],
    included: commonIncluded,
    excluded: commonExcluded,
    itinerary: [
      { day: 1, title: 'Drive to Nagarkot', description: 'Arrive at your hilltop resort and enjoy sunset views with dinner.' },
      { day: 2, title: 'Sunrise Viewpoint', description: 'Wake early for Himalayan sunrise, breakfast, and return transfer.' },
    ],
    isFeatured: true,
  },
  {
    title: 'Chitwan Jungle Safari Package',
    slug: 'chitwan-jungle-safari-package',
    location: 'Chitwan',
    category: 'Wildlife',
    shortDescription: "Safari drives, canoe rides, and Tharu culture in Nepal's most beloved national park.",
    description: 'Experience Chitwan National Park with guided jungle activities, wildlife viewing, river canoeing, and a cultural evening with the Tharu community.',
    price: 22000,
    durationDays: 3,
    durationNights: 2,
    maxGuests: 5,
    rating: 4.7,
    reviewsCount: 112,
    coverImage: image('photo-1549366021-9f761d450615'),
    images: [image('photo-1549366021-9f761d450615'), image('photo-1516426122078-c23e76319801'), image('photo-1521651201144-634f700b36ef')],
    amenities: ['Safari lodge', 'Full board meals', 'Naturalist guide', 'Park activities', 'Cultural show'],
    highlights: ['Jeep safari', 'Canoe ride', 'Tharu cultural program', 'Bird watching'],
    included: ['Accommodation', 'All meals', 'Safari activities', 'National park permits', 'Guide'],
    excluded: commonExcluded,
    itinerary: [
      { day: 1, title: 'Arrival and Village Walk', description: 'Check in, visit a Tharu village, and enjoy a cultural performance.' },
      { day: 2, title: 'Jungle Safari', description: 'Take a canoe ride, jungle walk, and jeep safari with a naturalist guide.' },
      { day: 3, title: 'Bird Watching', description: 'Morning bird watching followed by breakfast and departure.' },
    ],
    isFeatured: true,
  },
  {
    title: 'Everest View Luxury Trek',
    slug: 'everest-view-luxury-trek',
    location: 'Everest Region',
    category: 'Trekking',
    shortDescription: 'A comfortable trek through Sherpa villages with unforgettable Everest panoramas.',
    description: 'Walk classic Everest trails while staying in comfortable lodges, visiting Namche Bazaar, and enjoying close Himalayan views without committing to base camp.',
    price: 89000,
    durationDays: 7,
    durationNights: 6,
    maxGuests: 8,
    rating: 4.9,
    reviewsCount: 63,
    coverImage: image('photo-1544735716-392fe2489ffa'),
    images: [image('photo-1544735716-392fe2489ffa'), image('photo-1549880338-65ddcdfd017b'), image('photo-1500530855697-b586d89ba3ee')],
    amenities: ['Luxury lodges', 'Experienced guide', 'Porter support', 'Domestic flights', 'Trekking permits'],
    highlights: ['Everest viewpoints', 'Namche Bazaar', 'Sherpa culture', 'Scenic Lukla flight'],
    included: ['Lodging', 'Breakfast and dinner', 'Guide and porter', 'Permits', 'Kathmandu-Lukla flights'],
    excluded: ['Lunch on trek', 'Personal gear', 'Travel insurance', 'Emergency evacuation'],
    itinerary: [
      { day: 1, title: 'Fly to Lukla', description: 'Fly to Lukla and trek to Phakding through river valley trails.' },
      { day: 2, title: 'Trek to Namche', description: 'Climb through pine forests and suspension bridges to Namche Bazaar.' },
      { day: 3, title: 'Acclimatization', description: 'Explore Namche and hike to an Everest viewpoint.' },
      { day: 4, title: 'Trek to Thame', description: 'Walk through quieter Sherpa settlements with mountain views.' },
      { day: 5, title: 'Return to Namche', description: 'Enjoy a relaxed return trek and lodge evening.' },
      { day: 6, title: 'Trek to Lukla', description: 'Descend to Lukla for the final night in the region.' },
      { day: 7, title: 'Fly to Kathmandu', description: 'Morning flight back to Kathmandu.' },
    ],
    isFeatured: true,
  },
  {
    title: 'Annapurna Base Camp Trek',
    slug: 'annapurna-base-camp-trek',
    location: 'Annapurna Region',
    category: 'Trekking',
    shortDescription: 'A classic Himalayan trek into the Annapurna sanctuary with dramatic alpine scenery.',
    description: 'Journey through Gurung villages, rhododendron forests, and high mountain amphitheaters to reach Annapurna Base Camp.',
    price: 65000,
    durationDays: 8,
    durationNights: 7,
    maxGuests: 10,
    rating: 4.8,
    reviewsCount: 88,
    coverImage: image('photo-1486911278844-a81c5267e227'),
    images: [image('photo-1486911278844-a81c5267e227'), image('photo-1544735716-392fe2489ffa'), image('photo-1500530855697-b586d89ba3ee')],
    amenities: ['Tea house lodging', 'Guide', 'Porter support', 'Permits', 'Trail meals'],
    highlights: ['Annapurna Sanctuary', 'Machhapuchhre views', 'Gurung villages', 'Hot spring option'],
    included: ['Accommodation', 'Guide and porter', 'Permits', 'Ground transfers', 'Meals on trek'],
    excluded: ['Personal gear', 'Drinks', 'Insurance', 'Emergency evacuation'],
    itinerary: [
      { day: 1, title: 'Drive to Trailhead', description: 'Travel from Pokhara and start trekking through foothill villages.' },
      { day: 2, title: 'Forest Trails', description: 'Continue through rhododendron forest and terraced hillsides.' },
      { day: 3, title: 'Chhomrong Region', description: 'Enter the gateway villages of the sanctuary.' },
      { day: 4, title: 'Machhapuchhre Base Camp', description: 'Climb toward alpine scenery and dramatic peaks.' },
      { day: 5, title: 'Annapurna Base Camp', description: 'Reach ABC for sunrise and panoramic mountain views.' },
      { day: 6, title: 'Descend to Bamboo', description: 'Return through the sanctuary valley.' },
      { day: 7, title: 'Jhinu Danda', description: 'Descend toward hot springs and village lodging.' },
      { day: 8, title: 'Return to Pokhara', description: 'Complete the trek and drive back to Pokhara.' },
    ],
    isFeatured: true,
  },
  {
    title: 'Mustang Cultural Jeep Tour',
    slug: 'mustang-cultural-jeep-tour',
    location: 'Upper Mustang',
    category: 'Cultural',
    shortDescription: 'A rugged jeep journey through ancient walled towns, monasteries, and desert cliffs.',
    description: "Explore Upper Mustang's Tibetan-influenced culture, dramatic landscapes, and remote settlements with a guided overland itinerary.",
    price: 78000,
    durationDays: 6,
    durationNights: 5,
    maxGuests: 6,
    rating: 4.7,
    reviewsCount: 52,
    coverImage: image('photo-1526772662000-3f88f10405ff'),
    images: [image('photo-1526772662000-3f88f10405ff'), image('photo-1500530855697-b586d89ba3ee'), image('photo-1500534314209-a25ddb2bd429')],
    amenities: ['Private jeep', 'Local guide', 'Guesthouse lodging', 'Permits assistance', 'Breakfast'],
    highlights: ['Lo Manthang', 'Ancient monasteries', 'Kali Gandaki valley', 'Desert mountain landscapes'],
    included: commonIncluded,
    excluded: ['Restricted area permit', ...commonExcluded],
    itinerary: [
      { day: 1, title: 'Pokhara to Jomsom', description: 'Drive through the Kali Gandaki valley toward Mustang.' },
      { day: 2, title: 'Jomsom to Ghami', description: 'Continue through windswept villages and ochre cliffs.' },
      { day: 3, title: 'Lo Manthang', description: 'Explore the ancient walled capital and monasteries.' },
      { day: 4, title: 'Caves and Culture', description: 'Visit nearby caves, settlements, and cultural sites.' },
      { day: 5, title: 'Return to Jomsom', description: "Drive south through Mustang's high desert." },
      { day: 6, title: 'Back to Pokhara', description: 'Return drive to Pokhara.' },
    ],
    isFeatured: false,
  },
  {
    title: 'Kathmandu Heritage Tour',
    slug: 'kathmandu-heritage-tour',
    location: 'Kathmandu Valley',
    category: 'Cultural',
    shortDescription: "A compact cultural journey through Kathmandu's temples, courtyards, and old cities.",
    description: 'Discover UNESCO heritage sites across Kathmandu Valley with a knowledgeable city guide and comfortable transfers.',
    price: 12000,
    durationDays: 2,
    durationNights: 1,
    maxGuests: 6,
    rating: 4.5,
    reviewsCount: 130,
    coverImage: image('photo-1544735716-392fe2489ffa'),
    images: [image('photo-1544735716-392fe2489ffa'), image('photo-1526772662000-3f88f10405ff'), image('photo-1500534314209-a25ddb2bd429')],
    amenities: ['City hotel', 'Private guide', 'Private vehicle', 'Breakfast', 'Heritage entry support'],
    highlights: ['Kathmandu Durbar Square', 'Boudhanath', 'Pashupatinath', 'Patan old city'],
    included: commonIncluded,
    excluded: ['Monument entry fees', ...commonExcluded],
    itinerary: [
      { day: 1, title: 'Kathmandu Icons', description: 'Visit Pashupatinath, Boudhanath, and Kathmandu Durbar Square.' },
      { day: 2, title: 'Patan Heritage', description: "Explore Patan's courtyards, temples, and artisan lanes." },
    ],
    isFeatured: false,
  },
  {
    title: 'Bandipur Romantic Getaway',
    slug: 'bandipur-romantic-getaway',
    location: 'Bandipur',
    category: 'Honeymoon',
    shortDescription: 'A romantic hill town escape with heritage charm, quiet cafes, and mountain views.',
    description: 'Stay in atmospheric Bandipur with preserved Newari architecture, private dining touches, and easy walks to scenic viewpoints.',
    price: 16500,
    durationDays: 3,
    durationNights: 2,
    maxGuests: 2,
    rating: 4.7,
    reviewsCount: 58,
    coverImage: image('photo-1520250497591-112f2f40a3f4'),
    images: [image('photo-1520250497591-112f2f40a3f4'), image('photo-1500534314209-a25ddb2bd429'), image('photo-1501785888041-af3ef285b470')],
    amenities: ['Heritage hotel', 'Couple dinner', 'Breakfast', 'View room', 'Private transfer'],
    highlights: ['Bandipur bazaar', 'Sunset viewpoint', 'Heritage stay', 'Couple-friendly pace'],
    included: commonIncluded,
    excluded: commonExcluded,
    itinerary: [
      { day: 1, title: 'Arrival in Bandipur', description: 'Check in and stroll through the historic bazaar.' },
      { day: 2, title: 'Viewpoints and Leisure', description: 'Enjoy a slow day with viewpoints, cafes, and a special dinner.' },
      { day: 3, title: 'Departure', description: 'Breakfast and return transfer.' },
    ],
    isFeatured: false,
  },
  {
    title: 'Rara Lake Adventure Package',
    slug: 'rara-lake-adventure-package',
    location: 'Rara Lake',
    category: 'Adventure',
    shortDescription: "A remote adventure to Nepal's largest lake, framed by pine forests and high hills.",
    description: 'Travel to spectacular Rara Lake with guided logistics, remote lodging, forest walks, and sweeping views of clear blue alpine water.',
    price: 95000,
    durationDays: 7,
    durationNights: 6,
    maxGuests: 8,
    rating: 4.9,
    reviewsCount: 41,
    coverImage: image('photo-1501785888041-af3ef285b470'),
    images: [image('photo-1501785888041-af3ef285b470'), image('photo-1500534314209-a25ddb2bd429'), image('photo-1504280390367-361c6d9f38f4')],
    amenities: ['Remote logistics', 'Guide', 'Basic lodging', 'Permits', 'Meals'],
    highlights: ['Rara Lake', 'Remote Karnali landscapes', 'Forest walks', 'Adventure travel'],
    included: ['Accommodation', 'Meals', 'Guide', 'Permits', 'Domestic transport support'],
    excluded: ['Flight delays and extras', 'Personal gear', 'Insurance', 'Emergency evacuation'],
    itinerary: [
      { day: 1, title: 'Travel to Nepalgunj', description: 'Begin the journey west with overnight logistics.' },
      { day: 2, title: 'Toward Rara Region', description: 'Continue by flight and vehicle toward the lake region.' },
      { day: 3, title: 'Reach Rara Lake', description: 'Walk into the lake area and settle into remote lodging.' },
      { day: 4, title: 'Lake Exploration', description: 'Spend a full day exploring viewpoints and lakeside trails.' },
      { day: 5, title: 'Forest and Villages', description: 'Visit surrounding forests and local settlements.' },
      { day: 6, title: 'Return Journey', description: 'Begin the return route from Rara.' },
      { day: 7, title: 'Back to Kathmandu', description: 'Complete return logistics.' },
    ],
    isFeatured: true,
  },
  {
    title: 'Ghandruk Village Homestay',
    slug: 'ghandruk-village-homestay',
    location: 'Ghandruk',
    category: 'Cultural',
    shortDescription: 'A warm Gurung village stay with mountain views and authentic local hospitality.',
    description: "Experience Ghandruk's stone lanes, Gurung culture, and Annapurna views with a comfortable homestay and guided village walks.",
    price: 14500,
    durationDays: 3,
    durationNights: 2,
    maxGuests: 6,
    rating: 4.6,
    reviewsCount: 77,
    coverImage: image('photo-1500530855697-b586d89ba3ee'),
    images: [image('photo-1500530855697-b586d89ba3ee'), image('photo-1486911278844-a81c5267e227'), image('photo-1500534314209-a25ddb2bd429')],
    amenities: ['Homestay', 'Local meals', 'Village guide', 'Ground transfer', 'Mountain view'],
    highlights: ['Gurung culture', 'Annapurna views', 'Village walks', 'Local food'],
    included: commonIncluded,
    excluded: commonExcluded,
    itinerary: [
      { day: 1, title: 'Drive and Walk to Ghandruk', description: 'Travel from Pokhara and reach the village for a homestay dinner.' },
      { day: 2, title: 'Village Experience', description: 'Explore Ghandruk, visit the museum, and enjoy mountain views.' },
      { day: 3, title: 'Return to Pokhara', description: 'Breakfast and return transfer.' },
    ],
    isFeatured: false,
  },
  {
    title: 'Lumbini Peace Tour',
    slug: 'lumbini-peace-tour',
    location: 'Lumbini',
    category: 'Cultural',
    shortDescription: 'A peaceful short tour around sacred gardens, monasteries, and Buddhist heritage.',
    description: 'Visit the birthplace of Buddha with a calm itinerary through the Maya Devi Temple, monastic zones, and reflective garden spaces.',
    price: 13500,
    durationDays: 2,
    durationNights: 1,
    maxGuests: 5,
    rating: 4.4,
    reviewsCount: 49,
    coverImage: image('photo-1526772662000-3f88f10405ff'),
    images: [image('photo-1526772662000-3f88f10405ff'), image('photo-1500534314209-a25ddb2bd429'), image('photo-1506126613408-eca07ce68773')],
    amenities: ['Hotel stay', 'Guide', 'Breakfast', 'Private transfer', 'Monastery visits'],
    highlights: ['Maya Devi Temple', 'Peace Pagoda', 'Monastic zone', 'Sacred Garden'],
    included: commonIncluded,
    excluded: ['Monument entry fees', ...commonExcluded],
    itinerary: [
      { day: 1, title: 'Sacred Garden', description: 'Visit Maya Devi Temple and the surrounding sacred garden.' },
      { day: 2, title: 'Monastery Circuit', description: 'Explore the monastic zone and Peace Pagoda before departure.' },
    ],
    isFeatured: false,
  },
  {
    title: 'Dhulikhel Family Nature Stay',
    slug: 'dhulikhel-family-nature-stay',
    location: 'Dhulikhel',
    category: 'Family',
    shortDescription: 'A gentle family break with nature walks, mountain views, and relaxed resort time.',
    description: 'Take the family to Dhulikhel for fresh air, short hikes, comfortable rooms, and easy access from Kathmandu.',
    price: 11000,
    durationDays: 2,
    durationNights: 1,
    maxGuests: 5,
    rating: 4.5,
    reviewsCount: 68,
    coverImage: image('photo-1493809842364-78817add7ffb'),
    images: [image('photo-1493809842364-78817add7ffb'), image('photo-1500534314209-a25ddb2bd429'), image('photo-1501785888041-af3ef285b470')],
    amenities: ['Family room', 'Breakfast', 'Garden space', 'Private transfer', 'Kid-friendly meals'],
    highlights: ['Short family hikes', 'Himalayan views', 'Quiet resort stay', 'Easy Kathmandu access'],
    included: commonIncluded,
    excluded: commonExcluded,
    itinerary: [
      { day: 1, title: 'Arrival and Nature Walk', description: 'Drive to Dhulikhel and take a gentle family nature walk.' },
      { day: 2, title: 'Sunrise and Return', description: 'Enjoy sunrise views, breakfast, and return to Kathmandu.' },
    ],
    isFeatured: false,
  },
  {
    title: 'Bardia Wildlife Lodge Escape',
    slug: 'bardia-wildlife-lodge-escape',
    location: 'Bardia',
    category: 'Wildlife',
    shortDescription: 'A quieter jungle experience for travelers seeking wild landscapes and expert naturalists.',
    description: "Explore Bardia National Park with guided jungle walks, jeep safari, and lodge hospitality in Nepal's western Terai.",
    price: 42000,
    durationDays: 4,
    durationNights: 3,
    maxGuests: 6,
    rating: 4.8,
    reviewsCount: 37,
    coverImage: image('photo-1516426122078-c23e76319801'),
    images: [image('photo-1516426122078-c23e76319801'), image('photo-1549366021-9f761d450615'), image('photo-1521651201144-634f700b36ef')],
    amenities: ['Jungle lodge', 'Naturalist guide', 'All meals', 'Safari activities', 'Transfers'],
    highlights: ['Bardia National Park', 'Jeep safari', 'Jungle walk', 'River habitat'],
    included: ['Accommodation', 'All meals', 'Guide', 'Park activities', 'Permits'],
    excluded: commonExcluded,
    itinerary: [
      { day: 1, title: 'Arrive in Bardia', description: 'Check into the lodge and meet your naturalist guide.' },
      { day: 2, title: 'Safari Day', description: 'Full day jeep safari and wildlife tracking.' },
      { day: 3, title: 'Jungle Walk', description: 'Guided jungle walk and river habitat exploration.' },
      { day: 4, title: 'Departure', description: 'Breakfast and transfer onward.' },
    ],
    isFeatured: false,
  },
];

const seedPackages = async () => {
  const mongoUri = process.env.MONGODB_URI || process.env.MONGO_URI;
  if (!mongoUri) {
    throw new Error('MONGODB_URI is required to seed packages');
  }

  await mongoose.connect(mongoUri);

  for (const packageItem of packages) {
    await Package.findOneAndUpdate(
      { slug: packageItem.slug },
      { $set: { country: 'Nepal', currency: 'NPR', isPublished: true, ...packageItem } },
      { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true }
    );
  }

  const count = await Package.countDocuments();
  console.log(`Seeded ${packages.length} packages. Database now has ${count} packages.`);
  await mongoose.disconnect();
};

seedPackages().catch(async (error) => {
  console.error('Package seed failed:', error);
  await mongoose.disconnect();
  process.exit(1);
});
